#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title                       : Introduction to Cultural Analytics & Python  # The title of the book. Will be placed in the left navbar.
author                      : <a href="https://melaniewalsh.org/">Melanie Walsh</a>  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : "images/logo/favicon.ico"  # A path to the book logo
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "**/in-progress", "**/other_files", "features", "scraps"]

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "off"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                   : 30    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : True # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

#######################################################################################
# Parse and render settings
parse:
  myst_extended_syntax      : true  # enable MyST extended syntax support (see documents for details)
  myst_url_schemes          : [mailto, http, https]  # URI schemes that will be recognised as external URLs in Markdown links

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "images/logo/favicon.ico"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  #Will be displayed underneath the left navbar.
  extra_footer              : |
    <div>
    <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img class="license" alt="Creative Commons License" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a> This book is licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0 License</a>. The code is licensed under a <a href="https://choosealicense.com/licenses/gpl-3.0/#">GNU General Public License v3.0</a>.
    </div>
    
  google_analytics_id       : "UA-86905362-3"  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://melaniewalsh.github.io/Intro-Cultural-Analytics"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false


#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
#  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
#  thebe                     : False  # Add a thebe button to pages (requires the repository to run on Binder)
#  colab_url                 : False # The URL of Google Colab (e.g., https://colab.research.google.com)

repository:
  url                       : https://github.com/melaniewalsh/Intro-Cultural-Analytics  # The URL to your book's repository
  path_to_book              : "book"  # A path to your book's folder, relative to the repository root.
  branch                    : "master"  # Which branch of the repository should be used when creating links

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions: 
    - sphinx_inline_tabs
#  - sphinx_reredirects 
    - notfound.extension
  # A list of extra extensions to load by Sphinx (added to those already used by JB).
  config:
      myst_enable_extensions: 
      - amsmath
      - colon_fence
      - deflist
      - dollarmath
      - html_image
      - replacements
      - smartquotes
      - substitution
    #redirects:
      #"features/*": "https://melaniewalsh.github.io/Intro-Cultural-Analytics/$source.html"
      notfound_context:
         body: "<h1>Page not found.</h1>\n\nSorry, this page cannot be found. Try the <a href='index.html'> home page </a> or <a href='search.html'> search page </a> to find what you're looking for.</p>."
      notfound_no_urls_prefix: True
